### ISSUE TITLE
Docker compose building order with phpfpm and nginx

### ISSUE THREAD

**Issue by coolfarmer** [bitnami/bitnami-docker-symfony#67]
**Description**
Imagine you want to start a new project with this docker-compose:
```
version: '2'

services:
  bitnami3:
    image: 'bitnami/symfony:1'
    volumes:
      - '.:/app'
    environment:
      - TZ=America/New_York
      - SYMFONY_PROJECT_NAME=bitnami3
    networks:
      - default
  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '8784:8080'
    networks:
      - default
    depends_on:
      - bitnami3
    volumes:
      - './bitnami3:/app/bitnami3'
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - default
    volumes:
      - './bitnami3:/app/bitnami3'
    depends_on:
      - bitnami3

networks:
  default:
    driver: bridge
```

You will end up with this message when launching docker-compose up:
```
bitnami3_1  | Installing symfony/skeleton (v5.0.99)
bitnami3_1  |
bitnami3_1  |
bitnami3_1  |   [InvalidArgumentException]
bitnami3_1  |   Project directory bitnami3/ is not empty.
bitnami3_1  |
bitnami3_1  |
bitnami3_1  | create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
bitnami3_1  |
bitnami3_bitnami3_1 exited with code 1
```
Service **phpfpm** and **nginx** are builded too early, they create a folder inside the directory and then when the main service have to install symfony we end up with **"Project directory bitnami3/ is not empty."**

**Steps to reproduce the issue:**

1. Create new project folder
2. Create docker-compose file with my above example
3. Run docker-compose up

The workaround is to build the project without phpfpm/nginx THEN with them. But I hate this workaround, if I have to share my compose with a friend, they need to do that workaround and it's pretty bad.

How can I run this compose without this problem?

Windows 10
Docker Desktop 2.2.0.0

Thanks.

**Comment by sameersbn** [comment]
@coolfarmer Looks like the issue you're seeing is specific to the Windows Docker platform because I am unable to reproduce it on Linux using the docker-compose file your have listed.

However, please note that the symphony container starts a php app server internally and therefore you really don't need to use a php-fpm and nginx server for development purposes.

```yaml
version: '2'

services:
  bitnami3:
    image: 'bitnami/symfony:1'
    volumes:
      - '.:/app'
    environment:
      - TZ=America/New_York
      - SYMFONY_PROJECT_NAME=bitnami3
    networks:
      - default
    ports:
      - 8000:8000

networks:
  default:
    driver: bridge
```

However if you want to continue using your existing docker-compose.yaml file, changing the volume mount should probably fix the issue

```yaml
version: '2'

services:
  bitnami3:
    image: 'bitnami/symfony:1'
    volumes:
      - '.:/app'
    environment:
      - TZ=America/New_York
      - SYMFONY_PROJECT_NAME=bitnami3
    networks:
      - default
  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '8784:8080'
    networks:
      - default
    depends_on:
      - bitnami3
    volumes:
      - '.:/app'
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - default
    volumes:
      - '.:/app'
    depends_on:
      - bitnami3

networks:
  default:
    driver: bridge
```
